-- SunlessRP Sync Core (SERVER)
-- Sends CDN manifest version to clients for Gluapack-aware FastDL sync

-- This file is auto-generated by your builder:
-- lua/autorun/sunless_cdn_manifest.lua
-- It defines: SunlessCDN_ManifestVersion = <timestamp>

if not SunlessCDN_ManifestVersion then
    print("[SunlessCDN] WARNING: No manifest version found on server.")
end

util.AddNetworkString("SunlessCDN_Version")

hook.Add("PlayerInitialSpawn", "SunlessCDN_SendVersion", function(ply)
    net.Start("SunlessCDN_Version")
        net.WriteUInt(SunlessCDN_ManifestVersion or 0, 32)
    net.Send(ply)

    print("[SunlessCDN] Sent CDN version " .. tostring(SunlessCDN_ManifestVersion) .. " to " .. ply:Nick())
end)
